name: CI-Build

on: [push]

jobs:
  deploy:
    name: Verify
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Verify with Maven
      run: mvn -B verify --file pom.xml

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Send code to S3
      env:
        AWS_S3_CODE_BUCKET: ${{ secrets.AWS_S3_CODE_BUCKET }}
      run: |
        echo $GITHUB_REPOSITORY
        echo $GITHUB_SHA
        echo $GITHUB_SHA > release
        if test "$GITHUB_REF" = "refs/heads/main"; then
          echo "Branch is main - no need to make a release name..."
          branch="main"
        else
          echo "Making a release name for non-main branch..."
          branch=`echo $GITHUB_REF | awk -F '/' '{print $3}'`
          release_name=`echo $GITHUB_ACTOR-$branch`
          echo "Release name: $release_name"
          echo $release_name > release_name
        fi
        artifact=`grep "<artifactId" pom.xml | head -n 1 | awk -F"<artifactId>" '{print $2}' | awk -F "</artifactId" '{print $1}'`
        version=`grep "<version" pom.xml | head -n 1 | awk -F"<version>" '{print $2}' | awk -F "</version" '{print $1}'`
        version_tag=$artifact-$version-$branch-$GITHUB_SHA
        echo "Image version tag: $version_tag"
        echo $version_tag > image_tags
        zip -r app.zip .
        repo_slug=`echo $GITHUB_REPOSITORY | awk -F '/' '{print $2}'`
        echo $repo_slug
        aws s3 cp app.zip s3://$AWS_S3_CODE_BUCKET/$repo_slug.zip

    - name: Send build success notification
      if: success()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_MESSAGE: ${{ github.repository }} build ${{ github.run_number }} launched by ${{ github.actor }} has succeeded
        SLACK_TITLE: Build Success
        SLACK_CHANNEL: city-modelling-feeds
        SLACK_USERNAME: GitHub Build Bot
        SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send build failure notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: ${{ github.repository }} build ${{ github.run_number }} launched by ${{ github.actor }} has failed
        SLACK_TITLE: Build Failure!
        SLACK_CHANNEL: city-modelling-feeds
        SLACK_USERNAME: GitHub Build Bot
        SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
