name: CI-Build

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Verify with Maven
      run: mvn -B verify --file pom.xml

    - name: Send build success notification
      if: success()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_MESSAGE: ${{ github.repository }} build ${{ github.run_number }} launched by ${{ github.actor }} has succeeded
        SLACK_TITLE: Build Success
        SLACK_CHANNEL: city-modelling-feeds
        SLACK_USERNAME: GitHub Build Bot
        SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - name: Send build failure notification
      if: failure()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_COLOR: '#FF0000'
        SLACK_MESSAGE: ${{ github.repository }} build ${{ github.run_number }} launched by ${{ github.actor }} has failed
        SLACK_TITLE: Build Failure!
        SLACK_CHANNEL: city-modelling-feeds
        SLACK_USERNAME: GitHub Build Bot
        SLACK_ICON: https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2017-12-19/288981919427_f45f04edd92902a96859_512.png
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
