name: CI-Build

on: [push]

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.make-image-tags.outputs.IMAGE_TAG }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Verify with Maven
      run: mvn -B verify --file pom.xml
      id: maven-verify

    - name: Make image tags
      id: make-image-tags
      run: |
        artifact=`grep "<artifactId" pom.xml | head -n 1 | awk -F"<artifactId>" '{print $2}' | awk -F "</artifactId" '{print $1}'`
        version=`grep "<version" pom.xml | head -n 1 | awk -F"<version>" '{print $2}' | awk -F "</version" '{print $1}'`
        version_tag=$artifact-$version-$branch-$GITHUB_SHA
        echo "Image version tag: $version_tag"
        echo "IMAGE_TAG=$version_tag" >> "$GITHUB_OUTPUT"

    - name: Remove target dir
      run: |
        rm -rf target

  aws-upload:
    needs: verify
    if: needs.verify.result == 'success'
    uses: arup-group/actions-city-modelling-lab/.github/workflows/aws-upload.yml@main
    secrets: inherit
    with:
      image-tag: ${{ needs.verify.outputs.image-tag }}

  slack-notify-ci:
    needs: verify
    if: always()
    uses: arup-group/actions-city-modelling-lab/.github/workflows/slack-notify.yml@main
    secrets: inherit
    with:
      result: ${{ needs.verify.result }}
      channel: city-modelling-feeds
      message: CI build
